### PR TITLE
fix: upped statamic version

### PR DESCRIPTION
**Pull request by duncan412**

### CODE REVIEW

**Comment by benmAltDesign** [comment]
Hey Duncan, Thanks for this, we'll get a release out soon with this change

**Comment by ceesvanegmond** [comment]
@benmAltDesign When are you going to release this as a new version? Would be great if you could that soon!

**Comment by Alt-Ben** [comment]
Hey @ceesvanegmond!

We've run into some issues during testing around the data not saving as intended, as soon as we've sorted that, we'll get it released!

Cheers!

Ben

**Comment by ceesvanegmond** [comment]
Let me know! We could also do some testing

**Pull request merged**
